// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIiabejCp2VgHghPBH1Rgvarmyc_ecazI',
    appId: '1:639418027775:web:227a2e383354a601fd86ca',
    messagingSenderId: '639418027775',
    projectId: 'login-register-459fe',
    authDomain: 'login-register-459fe.firebaseapp.com',
    storageBucket: 'login-register-459fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXHP70SDfG6CC45C3JBi48fmW2dC1W1AE',
    appId: '1:639418027775:android:9e8dab1878085c9cfd86ca',
    messagingSenderId: '639418027775',
    projectId: 'login-register-459fe',
    storageBucket: 'login-register-459fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC2VHIcQbuFFLyM1h-3ymKLmOCoLPhoEM',
    appId: '1:639418027775:ios:6f380283fe9ff28ffd86ca',
    messagingSenderId: '639418027775',
    projectId: 'login-register-459fe',
    storageBucket: 'login-register-459fe.appspot.com',
    iosBundleId: 'com.example.loginRegisterUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC2VHIcQbuFFLyM1h-3ymKLmOCoLPhoEM',
    appId: '1:639418027775:ios:6f380283fe9ff28ffd86ca',
    messagingSenderId: '639418027775',
    projectId: 'login-register-459fe',
    storageBucket: 'login-register-459fe.appspot.com',
    iosBundleId: 'com.example.loginRegisterUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIiabejCp2VgHghPBH1Rgvarmyc_ecazI',
    appId: '1:639418027775:web:2df504725f05037ffd86ca',
    messagingSenderId: '639418027775',
    projectId: 'login-register-459fe',
    authDomain: 'login-register-459fe.firebaseapp.com',
    storageBucket: 'login-register-459fe.appspot.com',
  );
}
